### ISSUE TITLE
Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'Firebase.RemoteConfig'.\

### ISSUE THREAD

**Issue by maonaoda** [AdamEssenmacher/GoogleApisForiOSComponents#36]
Can not use this 
**Firebase.RemoteConfig.RemoteConfig.SharedInstance.ConfigSettings = new Firebase.RemoteConfig.RemoteConfigSettings();**
for ios device.

```
ObjCRuntime.RuntimeException: Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'Firebase.RemoteConfig'.
at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105
at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 93
at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 199
at ObjCRuntime.Class.ResolveToken(Assembly assembly, Module module, UInt32 token) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 521
at ObjCRuntime.Class.ResolveFullTokenReference(UInt32 token_reference) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 449
at ObjCRuntime.Class.ResolveTokenReference(UInt32 token_reference, UInt32 implicit_token_type) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 486
at ObjCRuntime.Class.ResolveTypeTokenReference(UInt32 token_reference) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 454
at ObjCRuntime.Class.FindType(NativeHandle class, Boolean& is_custom_type) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 423
at ObjCRuntime.Class.Lookup(IntPtr klass, Boolean throw_on_error) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 222
at ObjCRuntime.Class.Lookup(IntPtr klass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 213
at ObjCRuntime.Runtime.GetNSObject[RemoteConfig](IntPtr ptr, IntPtr sel, RuntimeMethodHandle method_handle, Boolean evenInFinalizerQueue)
at ObjCRuntime.Runtime.GetNSObject[RemoteConfig](IntPtr ptr, IntPtr sel, RuntimeMethodHandle method_handle)
at ObjCRuntime.Runtime.GetNSObject[RemoteConfig](IntPtr ptr)
at Firebase.RemoteConfig.RemoteConfig.get_SharedInstance()
```

**Comment by AdamEssenmacher** [comment]
https://github.com/xamarin/xamarin-macios/wiki/.NET-9-release-notes#type-registrar-managed-static-as-the-new-default ?

**Comment by maonaoda** [comment]
Maybe that's the problem,
I should have been trying net9.0-ios at the time.
