### ISSUE TITLE
Crash on .NET9

### ISSUE THREAD

**Issue by awasilik** [AdamEssenmacher/GoogleApisForiOSComponents#56]
Repro:

- Create empty MAUI app from template using .NET9
- Add PackageReference Include="AdamE.Firebase.iOS.Core" Version="[10.29.0.1]"
- Run the app

App crashes on startup with:
```
Launched application 'XXX' on 'iPhone (Phonies)' with pid 83495
dyld[83495]: Library not loaded: @rpath/FirebaseInstallations.framework/FirebaseInstallations
  Referenced from: <81D40DBC-0F7D-326C-BC2E-BC33D7A63950> /private/var/containers/Bundle/Application/31C5F9A5-474A-4615-A8D1-81670D00B205/TestMauiApp.app/Frameworks/FirebaseSessions.framework/FirebaseSessions
  Reason: tried: '/usr/lib/swift/FirebaseInstallations.framework/FirebaseInstallations' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FirebaseInstallations.framework/FirebaseInstallations' (no such file), '/private/var/containers/Bundle/Application/31C5F9A5-474A-4615-A8D1-81670D00B205/TestMauiApp.app/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' (no such file), '/private/var/containers/Bundle/Application/31C5F9A5-474A-4615-A8D1-81670D00B205/TestMauiApp.app/Frameworks/FirebaseSessions.framework/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' (no such file), '/private/var/containers/Bundle/Application/31C5F9A5-474A-4615-A8D1-81670D00B205/TestMauiApp.app/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' (no such file), '/private/var/containers/Bundle/Application/31C5F9A5-474A-4615-A8D1-81670D00B205/TestMauiApp.app/Frameworks/FirebaseInstallations.framework/FirebaseInstallations' (no such file)
Application 'com.zooomies.fraps' terminated (with exit code '' and/or crashing signal '6).
```

iPhone XS with iOS16.6

**Comment by miko1258** [comment]
Reproduced on iPhone 15 Pro Max, iOS 17.5.1

**Comment by dartasen** [comment]
Can reproduce that as well on my end

**Comment by AdamEssenmacher** [comment]
> - Add

Add what? There are over a dozen nugets published from this project.

Does it work with .net 8?

Have you tried adding the AdamE.Firebase.iOS.Installations package?

**Comment by awasilik** [comment]
Sorry, I udpated the repro. 
No I didn't, I use Plugin.Firebase for that, this was just minimal reproduction steps needed for the crash.
If installations is needed, shouldn't it be a reference to the core nuget?

**Comment by AdamEssenmacher** [comment]
OK try adding the Installations package and see if it works.

**Comment by awasilik** [comment]
Sorry for late reply. I had a pretty busy week. 
I added the package and it still crashes, but now with different result and it's not on app startup, but hen setting up firestore.
```
*** Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException', reason: 'Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'Firebase.CloudFirestore'. (ObjCRuntime.RuntimeException)
   at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105
   at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 93
   at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 199
   at ObjCRuntime.Class.ResolveToken(Assembly assembly, Module module, UInt32 token) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 521
   at ObjCRuntime.Class.ResolveFullTokenReference(UInt32 token_reference) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 449
   at ObjCRuntime.Class.ResolveTokenReference(UInt32 token_reference, UInt32 implicit_token_type) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 486
   at ObjCRuntime.Class.ResolveTypeTokenReference(UInt32 token_reference) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 454
   at ObjCRuntime.Class.FindType(NativeHandle class, Boolean& is_custom_type) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 423
   at ObjCRuntime.Class.Lookup(IntPtr klass, Boolean throw_on_error) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 222
   at ObjCRuntime.Class.Lookup(IntPtr klass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 213
   at ObjCRuntime.Runtime.GetNSObject[Firestore](IntPtr ptr, IntPtr sel, RuntimeMethodHandle method_handle, Boolean evenInFinalizerQueue) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1882
   at ObjCRuntime.Runtime.GetNSObject[Firestore](IntPtr ptr, IntPtr sel, RuntimeMethodHandle method_handle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1860
   at ObjCRuntime.Runtime.GetNSObject[Firestore](IntPtr ptr) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1855
   at Firebase.CloudFirestore.Firestore.get_SharedInstance()
   at Plugin.Firebase.Firestore.FirebaseFirestoreImplementation..ctor()
   at Plugin.Firebase.Firestore.CrossFirebaseFirestore.CreateInstance()
   at System.Lazy`1[[Plugin.Firebase.Firestore.IFirebaseFirestore, Plugin.Firebase.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].PublicationOnlyViaFactory(LazyHelper initializer)
   at System.Lazy`1[[Plugin.Firebase.Firestore.IFirebaseFirestore, Plugin.Firebase.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
   at System.Lazy`1[[Plugin.Firebase.Firestore.IFirebaseFirestore, Plugin.Firebase.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Value()
   at Plugin.Firebase.Firestore.CrossFirebaseFirestore.get_Current()
   at Zoomies.BusinessLayer.Database.FireStoreSetup.Setup() in /Users/ADWA/zoomies/Zoomies/Zoomies.BusinessLayer/Database/FireStoreSetup.cs:line 9
   at Zoomies.FirebaseConfiguration.<>c.<UseFirebase>b__0_2(UIApplication app, NSDictionary launchOptions) in /Users/ADWA/zoomies/Zoomies/Zoomies/FirebaseConfiguration.cs:line 22
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass8_0.<FinishedLaunching>b__1(FinishedLaunching del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[FinishedLaunching](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.__Registrar_Callbacks__.callback_881_Microsoft_Maui_MauiUIApplicationDelegate_FinishedLaunching(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)
```

**Comment by awasilik** [comment]
Adding
```
<Target Name="SelectStaticRegistrar" AfterTargets="SelectRegistrar">
    <PropertyGroup Condition="'$(Registrar)' == 'managed-static'">
        <Registrar>static</Registrar>
    </PropertyGroup>
</Target>
```

To csproj seem to do the job, nevertheless, it's turned on for some reason (performance) and still seems like a defect, not sure if it's a problem with bindings or Plugin.Firebase. 

Feel free to close should you have any reasons to :)
If you have any other questions / comments I'm more than happy to assist :)

**Comment by AdamEssenmacher** [comment]
The registrar issue is most likely a bug in xamarin-macios:
https://github.com/xamarin/xamarin-macios/issues/21546

There's a known workaround, and there's nothing really actionable from this side, so I'll close the issue.
